name: Builder

on:
  push:
    branches:
        - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          echo ${GITHUB_TOKEN} | docker login -u ${GITHUB_ACTOR} --password-stdin docker.pkg.github.com
          docker pull 'docker.pkg.github.com/kbeckmann/archbuilder/archbuilder'
          docker tag docker.pkg.github.com/kbeckmann/archbuilder/archbuilder:latest archbuilder
          docker run --rm archbuilder yay --noconfirm -Syyu airspyhf-git
          docker run --rm archbuilder yay --noconfirm -Syyu soapyairspyhf-git
          docker run --rm archbuilder yay --noconfirm -Syyu netcdf proj appcsxcad-git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

